import { Pet, ScoringRule, StoreItem, GrowthConfig, BlindBoxItem } from './types';

export const PETS: Pet[] = [
  { id: 'piggy', name: '小猪猪', imageUrl: encodeURI('/pets/小猪猪Lv.1.jpg'), description: '爱吃爱睡的快乐小猪', color: '#FFD1DA' },
  { id: 'blue-cat', name: '蓝猫', imageUrl: encodeURI('/pets/蓝猫Lv.1.jpg'), description: '安静稳重的英短蓝猫', color: '#D1E9FF' },
  { id: 'corgi', name: '柯基', imageUrl: encodeURI('/pets/柯基Lv.1.jpg'), description: '短腿电臀的小柯基', color: '#FFF5BA' },
  { id: 'monkey', name: '猴子', imageUrl: encodeURI('/pets/猴子Lv.1.jpg'), description: '机灵的小猴子助手', color: '#FFE5D9' },
  { id: 'nine-tailed-fox', name: '九尾狐', imageUrl: encodeURI('/pets/九尾狐Lv.1.jpg'), description: '神秘高贵的九尾灵狐', color: '#E6E6FA' },
  { id: 'polar-bear', name: '北极熊', imageUrl: encodeURI('/pets/北极熊Lv.1.jpg'), description: '憨厚强壮的极地白熊', color: '#F4FAFF' },
  { id: 'succulent-elf', name: '多肉精灵', imageUrl: encodeURI('/pets/多肉精灵Lv.1.jpg'), description: '治愈系的多肉小精灵', color: '#DCEDC8' },
  { id: 'ragdoll-cat', name: '布偶猫', imageUrl: encodeURI('/pets/布偶猫Lv.1.jpg'), description: '仙气十足的布偶猫', color: '#F3E5F5' },
  { id: 'call-duck', name: '柯尔鸭', imageUrl: encodeURI('/pets/柯尔鸭Lv.1.jpg'), description: '圆润治愈的网红鸭', color: '#FFF5BA' },
  { id: 'shiba', name: '柴犬', imageUrl: encodeURI('/pets/柴犬Lv.1.jpg'), description: '活泼可爱的笑脸柴犬', color: '#FFE5D9' },
  { id: 'bichon', name: '比熊犬', imageUrl: encodeURI('/pets/比熊犬Lv.1.jpg'), description: '像棉花糖一样的比熊', color: '#F4FAFF' },
  { id: 'french-bulldog', name: '法斗犬', imageUrl: encodeURI('/pets/法斗犬Lv.1.jpg'), description: '憨萌可爱的法国斗牛犬', color: '#D1E9FF' },
  { id: 'unicorn', name: '独角兽', imageUrl: encodeURI('/pets/独角兽Lv.1.jpg'), description: '梦幻纯洁的独角兽', color: '#F3E5F5' },
  { id: 'tiger-baby', name: '白虎', imageUrl: encodeURI('/pets/白虎Lv.1.jpg'), description: '威风凛凛的小白虎', color: '#FFF5BA' },
  { id: 'budgie', name: '虎皮鹦鹉', imageUrl: encodeURI('/pets/虎皮鹦鹉Lv.1.jpg'), description: '羽色艳丽的小鹦鹉', color: '#DCEDC8' },
  { id: 'golden-retriever', name: '金毛', imageUrl: encodeURI('/pets/金毛Lv.1.jpg'), description: '暖心治愈的小金毛', color: '#FFF5BA' },
  { id: 'leopard-baby', name: '小花豹', imageUrl: encodeURI('/pets/小花豹Lv.1.jpg'), description: '矫健轻盈的小花豹', color: '#FFE5D9' },
  { id: 'vermilion-bird', name: '朱雀鸟', imageUrl: encodeURI('/pets/朱雀鸟Lv.1.jpg'), description: '祥瑞火焰的朱雀神鸟', color: '#FFCAD4' },
  { id: 'alpaca', name: '羊驼', imageUrl: encodeURI('/pets/羊驼Lv.1.jpg'), description: '呆萌可爱的网络神兽', color: '#F4FAFF' },
  { id: 'azure-dragon', name: '青龙', imageUrl: encodeURI('/pets/青龙Lv.1.jpg'), description: '威严神圣的东方青龙', color: '#D1E9FF' },
  { id: 'pixiu', name: '貔貅', imageUrl: encodeURI('/pets/貔貅Lv.1.jpg'), description: '招财进宝的吉祥兽', color: '#FFCAD4' },
  { id: 'teddy-dog', name: '泰迪犬', imageUrl: encodeURI('/pets/泰迪犬Lv.1.jpg'), description: '聪明活泼的卷毛狗狗', color: '#FFE5D9' },
  { id: 'panda', name: '熊猫', imageUrl: encodeURI('/pets/熊猫Lv.1.jpg'), description: '憨态可掬的国宝大熊猫', color: '#F4FAFF' },
  { id: 'silver-cat', name: '银渐层猫', imageUrl: encodeURI('/pets/银渐层猫Lv.1.jpg'), description: '优雅高贵的银渐层', color: '#D1E9FF' },
  { id: 'westie', name: '西高地犬', imageUrl: encodeURI('/pets/西高地犬Lv.1.jpg'), description: '活泼勇敢的白山梗', color: '#F4FAFF' },
  { id: 'golden-cat', name: '金渐层', imageUrl: encodeURI('/pets/金渐层Lv.1.jpg'), description: '软萌可爱的金渐层', color: '#FFF5BA' },
  { id: 'rabbit', name: '小白兔', imageUrl: encodeURI('/pets/小白兔Lv.1.jpg'), description: '温顺软绵的长耳兔', color: '#FFE5D9' },
  { id: 'pony', name: '小马驹', imageUrl: encodeURI('/pets/小马驹Lv.1.jpg'), description: '奔跑在草原的小骏马', color: '#FFF5BA' },
  { id: 'schnauzer', name: '雪纳瑞', imageUrl: encodeURI('/pets/雪纳瑞Lv.1.jpg'), description: '机灵勇敢的小老头狗', color: '#D1E9FF' },
  { id: 'red-panda', name: '小熊猫', imageUrl: encodeURI('/pets/小熊猫Lv.1.jpg'), description: '软糯可爱的红熊猫', color: '#FFE5D9' },
];

export const SCORING_RULES: ScoringRule[] = [
  // 学习 (Study)
  { id: 's1', category: 'study', label: '作业完成优秀', points: 1, type: 'plus', icon: 'Book' },
  { id: 's2', category: 'study', label: '平时测验满分', points: 3, type: 'plus', icon: 'Trophy' },
  { id: 's3', category: 'study', label: '平时测验优秀', points: 2, type: 'plus', icon: 'Star' },
  { id: 's4', category: 'study', label: '默写全对', points: 1, type: 'plus', icon: 'ClipboardCheck' },
  { id: 's7', category: 'study', label: '订正态度认真', points: 1, type: 'plus', icon: 'PenLine' },
  { id: 's8', category: 'study', label: '优秀作业,值得学习', points: 1, type: 'plus', icon: 'BookOpen' },
  { id: 's9', category: 'study', label: '近期学习状态进步', points: 1, type: 'plus', icon: 'Zap' },
  { id: 's10', category: 'study', label: '被老师点名表扬', points: 1, type: 'plus', icon: 'ThumbsUp' },
  { id: 's11', category: 'study', label: '单元测验显著进步', points: 2, type: 'plus', icon: 'Trophy' },
  
  { id: 's5', category: 'study', label: '不交作业', points: -1, type: 'minus', icon: 'FileX' },
  { id: 's6', category: 'study', label: '抄袭作业', points: -5, type: 'minus', icon: 'Scissors' },
  { id: 's12', category: 'study', label: '未完成作业', points: -2, type: 'minus', icon: 'BookX' },
  { id: 's13', category: 'study', label: '作业潦草', points: -1, type: 'minus', icon: 'Pen' },
  { id: 's14', category: 'study', label: '订正不认真', points: -2, type: 'minus', icon: 'PenLine' },
  { id: 's15', category: 'study', label: '考试作弊', points: -5, type: 'minus', icon: 'AlertTriangle' },
  { id: 's16', category: 'study', label: '学习显著退步', points: -2, type: 'minus', icon: 'TrendingDown' },

  // 行为 (Behavior)
  { id: 'b1', category: 'behavior', label: '早读认真专注', points: 1, type: 'plus', icon: 'Book' },
  { id: 'b2', category: 'behavior', label: '课前准备充分', points: 1, type: 'plus', icon: 'Backpack' },
  { id: 'b5', category: 'behavior', label: '眼保健操全程认真', points: 1, type: 'plus', icon: 'Smile' },
  { id: 'b6', category: 'behavior', label: '升旗仪式安静整齐', points: 1, type: 'plus', icon: 'Medal' },
  { id: 'b7', category: 'behavior', label: '守纪表现优秀(全天)', points: 2, type: 'plus', icon: 'ShieldCheck' },
  { id: 'b8', category: 'behavior', label: '主动帮助同学', points: 2, type: 'plus', icon: 'Users' },
  { id: 'b9', category: 'behavior', label: '拾金不昧(一般)', points: 2, type: 'plus', icon: 'Diamond' },
  { id: 'b10', category: 'behavior', label: '拾金不昧(贵重)', points: 5, type: 'plus', icon: 'Gem' },
  { id: 'b11', category: 'behavior', label: '主动帮助生病同学', points: 3, type: 'plus', icon: 'Heart' },
  { id: 'b12', category: 'behavior', label: '主动调解同学矛盾', points: 3, type: 'plus', icon: 'Handshake' },
  { id: 'b13', category: 'behavior', label: '做好人好事被表扬', points: 3, type: 'plus', icon: 'Award' },
  { id: 'b14', category: 'behavior', label: '积极参与校内外活动', points: 3, type: 'plus', icon: 'Star' },
  { id: 'b15', category: 'behavior', label: '犯错主动认错', points: 1, type: 'plus', icon: 'UserCheck' },

  { id: 'b16', category: 'behavior', label: '无故迟到或早退', points: -1, type: 'minus', icon: 'Clock' },
  { id: 'b17', category: 'behavior', label: '未佩戴红领巾/校徽', points: -1, type: 'minus', icon: 'Target' },
  { id: 'b18', category: 'behavior', label: '私自旷课或逃学', points: -3, type: 'minus', icon: 'Footprints' },
  { id: 'b19', category: 'behavior', label: '上课讲话、搞小动作', points: -1, type: 'minus', icon: 'Tv' },
  { id: 'b20', category: 'behavior', label: '扰乱课堂秩序', points: -3, type: 'minus', icon: 'Flame' },
  { id: 'b21', category: 'behavior', label: '课间追逐打闹', points: -3, type: 'minus', icon: 'Bike' },
  { id: 'b22', category: 'behavior', label: '追逐打闹(严重)', points: -3, type: 'minus', icon: 'Flame' },
  { id: 'b23', category: 'behavior', label: '中午自习说话', points: -1, type: 'minus', icon: 'Tv' },
  { id: 'b24', category: 'behavior', label: '私自带玩具到学校', points: -3, type: 'minus', icon: 'Box' },
  { id: 'b25', category: 'behavior', label: '排队时说话/插队', points: -1, type: 'minus', icon: 'Target' },
  { id: 'b26', category: 'behavior', label: '传播脏话或流言', points: -5, type: 'minus', icon: 'Music' },
  { id: 'b27', category: 'behavior', label: '撒谎、隐瞒真相', points: -2, type: 'minus', icon: 'Key' },
  { id: 'b28', category: 'behavior', label: '说脏话,骂人', points: -2, type: 'minus', icon: 'Tv' },
  { id: 'b29', category: 'behavior', label: '欺负、推搡同学', points: -10, type: 'minus', icon: 'Flame' },
  { id: 'b30', category: 'behavior', label: '挑拨离间、排挤他人', points: -3, type: 'minus', icon: 'Scissors' },
  { id: 'b31', category: 'behavior', label: '不尊重同学、起绰号', points: -3, type: 'minus', icon: 'Target' },
  { id: 'b32', category: 'behavior', label: '为私欲包庇他人错误', points: -3, type: 'minus', icon: 'Key' },
  { id: 'b33', category: 'behavior', label: '恶意举报、诬告他人', points: -3, type: 'minus', icon: 'Target' },
  { id: 'b34', category: 'behavior', label: '破坏校园设施', points: -5, type: 'minus', icon: 'Scissors' },

  // 健康 (Health)
  { id: 'h3', category: 'health', label: '认真完成包干区劳动', points: 1, type: 'plus', icon: 'Sparkles' },
  { id: 'h4', category: 'health', label: '主动为班级擦黑板', points: 1, type: 'plus', icon: 'PenTool' },
  { id: 'h5', category: 'health', label: '主动整理讲台', points: 1, type: 'plus', icon: 'Box' },
  { id: 'h6', category: 'health', label: '主动整理黑板粉笔', points: 1, type: 'plus', icon: 'PenTool' },
  { id: 'h7', category: 'health', label: '主动倒垃圾并套袋', points: 2, type: 'plus', icon: 'Box' },
  { id: 'h2', category: 'health', label: '座位整洁无涂画,桌椅整齐', points: 1, type: 'plus', icon: 'Star' },
  { id: 'h8', category: 'health', label: '座位周围无垃圾', points: 1, type: 'plus', icon: 'Sparkles' },

  { id: 'h9', category: 'health', label: '打扫包干区不认真', points: -2, type: 'minus', icon: 'Clock' },
  { id: 'h10', category: 'health', label: '个人座位卫生差', points: -1, type: 'minus', icon: 'Target' },
  { id: 'h11', category: 'health', label: '校园内乱扔垃圾', points: -1, type: 'minus', icon: 'Footprints' },
  { id: 'h12', category: 'health', label: '桌洞脏乱、塞废纸', points: -1, type: 'minus', icon: 'Box' },
  { id: 'h13', category: 'health', label: '破坏卫生、不洁手', points: -2, type: 'minus', icon: 'Palette' },
  { id: 'h14', category: 'health', label: '浪费粮食', points: -2, type: 'minus', icon: 'Utensils' },
  { id: 'h15', category: 'health', label: '破坏班级绿化', points: -3, type: 'minus', icon: 'Flower' },

  // 其他 (Other)
  { id: 'o1', category: 'other', label: '主动整理图书', points: 2, type: 'plus', icon: 'Book' },
  { id: 'o2', category: 'other', label: '主动帮同学更换水桶', points: 2, type: 'plus', icon: 'Anchor' },
  { id: 'o3', category: 'other', label: '主动承担班级任务', points: 2, type: 'plus', icon: 'Layout' },
  { id: 'o4', category: 'other', label: '积极参加班级墙报', points: 2, type: 'plus', icon: 'Palette' },
  { id: 'o5', category: 'other', label: '积极参加班级或校级晚会', points: 1, type: 'plus', icon: 'Star' },
  { id: 'o6', category: 'other', label: '活动中表现优秀', points: 2, type: 'plus', icon: 'Medal' },
  { id: 'o7', category: 'other', label: '代表班级参赛', points: 3, type: 'plus', icon: 'Trophy' },
  { id: 'o8', category: 'other', label: '校级比赛:一等奖', points: 5, type: 'plus', icon: 'Award' },
  { id: 'o9', category: 'other', label: '校级比赛:二等奖', points: 4, type: 'plus', icon: 'Award' },
  { id: 'o10', category: 'other', label: '校级比赛:三等奖', points: 3, type: 'plus', icon: 'Award' },
  { id: 'o11', category: 'other', label: '区级及以上:一等奖', points: 8, type: 'plus', icon: 'Crown' },
  { id: 'o12', category: 'other', label: '区级及以上:二等奖', points: 6, type: 'plus', icon: 'Crown' },
  { id: 'o13', category: 'other', label: '区级及以上:三等奖', points: 4, type: 'plus', icon: 'Crown' },
  { id: 'o14', category: 'other', label: '联欢会或文艺汇总演', points: 2, type: 'plus', icon: 'Music' },
  { id: 'o15', category: 'other', label: '为班级争得荣誉', points: 5, type: 'plus', icon: 'Wind' },
  { id: 'o16', category: 'other', label: '小组全周无违纪行为', points: 2, type: 'plus', icon: 'Handshake' },

  { id: 'o17', category: 'other', label: '损坏公物、不爱惜', points: -1, type: 'minus', icon: 'Scissors' },
  { id: 'o18', category: 'other', label: '浪费水电、不节约', points: -1, type: 'minus', icon: 'Zap' },
  { id: 'o19', category: 'other', label: '故意弄弄损坏班级公物', points: -3, type: 'minus', icon: 'Tv' },
  { id: 'o20', category: 'other', label: '故意损坏卫生间设施', points: -2, type: 'minus', icon: 'Scissors' },
  { id: 'o21', category: 'other', label: '扣分严重/屡教不改', points: -8, type: 'minus', icon: 'Flame' },

  // 幼儿园好习惯 (Kindergarten Habits)
  { id: 'k1', category: 'kindergarten', label: '独立睡觉+起床', points: 1, type: 'plus', icon: 'Moon' },
  { id: 'k2', category: 'kindergarten', label: '自己穿、脱衣服', points: 1, type: 'plus', icon: 'Shirt' },
  { id: 'k3', category: 'kindergarten', label: '每天主动刷牙洗脸', points: 1, type: 'plus', icon: 'Sparkles' },
  { id: 'k4', category: 'kindergarten', label: '不挑食吃饭认真', points: 1, type: 'plus', icon: 'Utensils' },
  { id: 'k5', category: 'kindergarten', label: '自己收拾玩具/内务', points: 1, type: 'plus', icon: 'Box' },
  { id: 'k6', category: 'kindergarten', label: '回家及食前洗手', points: 1, type: 'plus', icon: 'Droplets' },
  { id: 'k7', category: 'kindergarten', label: '21:30前上床不熬夜', points: 1, type: 'plus', icon: 'Clock' },
  { id: 'k8', category: 'kindergarten', label: '看电视不超过20分钟', points: 1, type: 'plus', icon: 'Tv' },
  { id: 'k9', category: 'kindergarten', label: '每天主动完成作业', points: 2, type: 'plus', icon: 'BookOpen' },
  { id: 'k10', category: 'kindergarten', label: '阅读1本绘本', points: 2, type: 'plus', icon: 'Book' },
  { id: 'k11', category: 'kindergarten', label: '认识新字20个', points: 2, type: 'plus', icon: 'GraduationCap' },
  { id: 'k12', category: 'kindergarten', label: '坐姿、握笔姿势标准', points: 3, type: 'plus', icon: 'PenTool' },
  { id: 'k13', category: 'kindergarten', label: '每天大声读书30分钟', points: 3, type: 'plus', icon: 'Megaphone' },
  { id: 'k14', category: 'kindergarten', label: '完成数学口算50题', points: 2, type: 'plus', icon: 'Calculator' },
  { id: 'k15', category: 'kindergarten', label: '分享小学里的事情', points: 2, type: 'plus', icon: 'MessageCircle' },
  { id: 'k16', category: 'kindergarten', label: '每天有学习计划', points: 2, type: 'plus', icon: 'Calendar' },
  { id: 'k17', category: 'kindergarten', label: '主动帮忙做家务', points: 1, type: 'plus', icon: 'Home' },
  { id: 'k18', category: 'kindergarten', label: '阳光运动2小时', points: 1, type: 'plus', icon: 'Sun' },
  { id: 'k19', category: 'kindergarten', label: '遇到问题想办法解决', points: 1, type: 'plus', icon: 'Lightbulb' },
  { id: 'k20', category: 'kindergarten', label: '不发脾气、有耐心', points: 1, type: 'plus', icon: 'Heart' },
  { id: 'k21', category: 'kindergarten', label: '学会轮滑/跳绳', points: 1, type: 'plus', icon: 'Activity' },
  { id: 'k22', category: 'kindergarten', label: '友爱兄弟姐妹', points: 1, type: 'plus', icon: 'Users' },
  { id: 'k23', category: 'kindergarten', label: '和长辈好好说话', points: 1, type: 'plus', icon: 'MessageSquare' },

  { id: 'k24', category: 'kindergarten', label: '嘴巴乱吃东西', points: -3, type: 'minus', icon: 'Pizza' },
  { id: 'k25', category: 'kindergarten', label: '说谎', points: -3, type: 'minus', icon: 'UserX' },
  { id: 'k26', category: 'kindergarten', label: '没理由地发脾气', points: -3, type: 'minus', icon: 'CloudLightning' },
  { id: 'k27', category: 'kindergarten', label: '摔东西', points: -3, type: 'minus', icon: 'Hammer' },
  { id: 'k28', category: 'kindergarten', label: '拖拉、磨蹭', points: -3, type: 'minus', icon: 'Timer' },
  { id: 'k29', category: 'kindergarten', label: '看电视时间超过30分钟', points: -3, type: 'minus', icon: 'Tv' },
];

export const DEFAULT_GROWTH_CONFIG: GrowthConfig[] = [
  { level: 1, pointsRequired: 40 },
  { level: 2, pointsRequired: 70 },
  { level: 3, pointsRequired: 100 },
  { level: 4, pointsRequired: 140 },
  { level: 5, pointsRequired: 180 },
  { level: 6, pointsRequired: 240 },
  { level: 7, pointsRequired: 0 }, // Max level
];

export const DEFAULT_STORE_ITEMS: StoreItem[] = [
  { id: 'st1', name: '免作业卡', price: 50, stock: 10, icon: 'FileText', description: '可抵消一次家庭作业，今晚可以早点休息啦！' },
  { id: 'st2', name: '前排座位卡', price: 30, stock: 5, icon: 'Monitor', description: '获得一周坐在黄金第一排的机会，听课更专注！' },
  { id: 'st3', name: '小零食', price: 10, stock: 50, icon: 'Cookie', description: '兑换一份美味可口的小零食，补充元气能量！' },
  { id: 'st4', name: '自选一天同桌', price: 40, stock: 5, icon: 'Users', description: '邀请你最想一起学习的小伙伴，当一天快乐同桌。' },
  { id: 'st5', name: '老师表扬卡', price: 20, stock: 20, icon: 'Sparkles', description: '在全班面前获得老师的正式表扬，荣誉值拉满！' },
  { id: 'st6', name: '班级小助手', price: 15, stock: 10, icon: 'Scissors', description: '化身小小值日生，协助老师管理班级，锻炼自我！' },
];

export const BLIND_BOX_UNLOCK_LEVEL = 3;
export const BLIND_BOX_COST = 20;

export const RARITY_CONFIG = {
  common: { name: '普通', color: 'text-gray-500', bgColor: 'bg-gray-100', weight: 60 },
  rare: { name: '稀有', color: 'text-blue-500', bgColor: 'bg-blue-100', weight: 25 },
  epic: { name: '史诗', color: 'text-purple-500', bgColor: 'bg-purple-100', weight: 10 },
  legendary: { name: '传说', color: 'text-yellow-500', bgColor: 'bg-yellow-100', weight: 5 },
};

export const BLIND_BOX_POOL: BlindBoxItem[] = [
  { id: 'item_xp_boost', name: '双倍经验卡', type: 'item', rarity: 'common', imageUrl: 'https://cdn-icons-png.flaticon.com/512/1162/1162456.png', description: '下次评价获得双倍成长值' },
  { id: 'item_protect', name: '扣分保护伞', type: 'item', rarity: 'rare', imageUrl: 'https://cdn-icons-png.flaticon.com/512/861/861057.png', description: '抵消一次扣分评价' },
  { id: 'pet_dragon', name: '小金龙', type: 'pet', rarity: 'legendary', imageUrl: 'https://cdn-icons-png.flaticon.com/512/3513/3513470.png', description: '极其罕见的传说pets' },
  { id: 'pet_phoenix', name: '冰晶凤凰', type: 'pet', rarity: 'epic', imageUrl: 'https://cdn-icons-png.flaticon.com/512/3513/3513481.png', description: '高贵的史诗pets' },
  { id: 'skin_cyber', name: '赛博皮卡', type: 'skin', rarity: 'epic', imageUrl: 'https://cdn-icons-png.flaticon.com/512/1162/1162499.png', description: '为你的pets换上未来感皮肤' },
  { id: 'skin_royal', name: '皇家礼服', type: 'skin', rarity: 'legendary', imageUrl: 'https://cdn-icons-png.flaticon.com/512/1162/1162520.png', description: '至尊传说品质的华丽服饰' },
];
